# Jekyll configuration for Open SDG platform

# primary settings:
baseurl: "/sdg-enz-staging-site" # change here!
remote_data_prefix: "https://DrJannisHoek.github.io/sdg-enz-staging-data/"

# URL for the "Edit Data" and "Edit Metadata" button on indicators.
data_edit_url: http://prose.io/#DrJannisHoek/sdg-enz-staging-data/edit/develop/data/indicator_[id].csv
metadata_edit_url: http://prose.io/#DrJannisHoek/sdg-enz-staging-data/edit/develop/meta/[id].md


# 
# other settings are alphabetically ordered:
analytics:
  ga_prod: ''

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

country: # or place name
  name: Enzkreis
  adjective: Enzkreis

create_indicators:
  layout: indicator
create_goals:
  previous_next_links: false
  goals: []
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search

custom_js:
  - /assets/js/custom.js
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE


footer_language_toggle: none
footer_menu:
  - path: https://sdg-enz-site.github.io/sdg-enz-data/de/zip/all_indicators.zip
    translation_key: Download
  - path: https://www.enzkreis.de/Landkreis-Politik/Leitbild-Agenda-2030/
    translation_key: menu.contact_us
  - path: https://www.enzkreis.de/Sonstiges/Impressum/
    translation_key: menu.cookies
  - path: /guidance
    translation_key: menu.guidance


frontpage_introduction_banner:
 title: my-custom-translations.frontpage-intro-title
 description: my-custom-translations.frontpage-intro-description

frontpage_goals_grid:
  title: my-custom-translations.my-goals-grid-title
  description: my-custom-translations.my-goals-grid-description


frontpage_cards:
  - title: Agenda 2030 im Enzkreis
    href: "https://www.enzkreis.de/Landkreis-Politik/Leitbild-Agenda-2030/" 
    thumbnail_src: /thumbnail_Agenda2030_Enzkreis.png
  - title: Agenda 2030 für Städte und Gemeinde
    href: "https://www.enzkreis.de/output/download.php?fid=3397.2189.1.PDF"
    thumbnail_src: /thumbnail_Agenda2030_StaedteundGemeinden.png
  - title: Prodcast "Transfer für die Ohren", Episode 1 (Transferagentur Bayern, Regionalbüro Süd):<br>Interview mit Dr. Jannis Hoek
    href: "https://open.spotify.com/episode/4hOCv6rGi0TDbJE5lUSOyW?si=6d16592196ce4000"
    thumbnail_src: /thumbnail_podcast.jpg
  - title: Indikatorenbericht 2023 (Downloadlink folgt nach Veröffentlichung)
    href: "https://www.enzkreis.de/output/download.php?fid=3397.3926.1.PDF"
    thumbnail_src: /thumbnail_indikatorenbericht2023.png


goal_image_base: https://open-sdg.org/sdg-translations/assets/img/goals
graph_color_set: 'custom'
graph_color_list: ['81ceea','fde55c','02aef0','fc9b29','0275f0','f07002','010984','e44501','010326','ae1901']
header_language_toggle: dropdown

languages:
  - de

menu:
  - path: /goals
    translation_key: general.goals
  - path: "https://www.enzkreis.de/Landkreis-Politik/Leitbild-Agenda-2030/"
    translation_key: menu.about

metadata_tabs:
  - scope: national
    title: Metadaten
    description: indicator.national_metadata_blurb

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

remote_theme: open-sdg/open-sdg@2.1.0

title: general.site_title
url: ""
environment: staging
